name: Continuous Integration
run-name: Build and Test by @${{ github.actor }}

on: 
  push:
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install packages
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: install
    
    - name: Run tests
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: test
    
    - name: Build the project
      uses: Borales/actions-yarn@v4.2.0
      with:
        cmd: build
    

